export { TreatmentsSection, NewsSection } from "./DashboardContent";
export { NextAppointmentWidget } from "./NextAppointmentWidget";
export { ClientJourneyStats } from "./ClientJourneyStats";
export { BeforeAfterPreview } from "./BeforeAfterPreview";
export { UnreadBanner } from "./UnreadBanner";
export { UpdateFiltersChips } from "./UpdateFiltersChips";
export { MonthNavigation } from "./MonthNavigation";
export { UpdatesStats } from "./UpdatesStats";
export { NextAppointmentCard } from "./NextAppointmentCard";
export { UpcomingAppointmentsList } from "./UpcomingAppointmentsList";
export { ContactCard } from "./ContactCard";
export { AppointmentHistory } from "./AppointmentHistory";
